// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_U-PZgt3qMsLQS44qiHogY3bkZxtRir8',
    appId: '1:936358713872:web:2865926a790e751f428895',
    messagingSenderId: '936358713872',
    projectId: 'tiktok-clone-bc75a',
    authDomain: 'tiktok-clone-bc75a.firebaseapp.com',
    storageBucket: 'tiktok-clone-bc75a.appspot.com',
    measurementId: 'G-LHPD9V65Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-gHoa3woC9NkfyCwUIbBZjTNYWW4rA4',
    appId: '1:936358713872:android:14e5b6e211315d4d428895',
    messagingSenderId: '936358713872',
    projectId: 'tiktok-clone-bc75a',
    storageBucket: 'tiktok-clone-bc75a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRy8L78_xfzCoLKIiZVM_TSVGamgTJIc',
    appId: '1:936358713872:ios:6214cc9c83c5d029428895',
    messagingSenderId: '936358713872',
    projectId: 'tiktok-clone-bc75a',
    storageBucket: 'tiktok-clone-bc75a.appspot.com',
    iosClientId: '936358713872-i148qbbv9ol552v8rrtrr8ui1538v8cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRy8L78_xfzCoLKIiZVM_TSVGamgTJIc',
    appId: '1:936358713872:ios:295749e9f0f3418a428895',
    messagingSenderId: '936358713872',
    projectId: 'tiktok-clone-bc75a',
    storageBucket: 'tiktok-clone-bc75a.appspot.com',
    iosClientId: '936358713872-2slv2cen7e0tgrtpb6aiv8o9k3igibl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
